// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    App404: typeof import('./../app/views/app-404.vue')['default']
    AppButton: typeof import('./../app/components/shared/AppButton.vue')['default']
    AppCard: typeof import('./../app/components/AppCard.vue')['default']
    AppNavbar: typeof import('./../app/components/AppNavbar.vue')['default']
    LayoutSidebar: typeof import('./../app/layouts/layout-sidebar.vue')['default']
    PagesIndex: typeof import('./../pages/views/pages-index.vue')['default']
    PagesShow: typeof import('./../pages/views/pages-show.vue')['default']
    VButton: typeof import('./../app/components/shared/VButton.vue')['default']
    VCard: typeof import('./../app/components/VCard.vue')['default']
    VNavbar: typeof import('./../components/VNavbar.vue')['default']
  }
}

export { }
