// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./../components/shared/ButtonPrimary.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    Card: typeof import('./../components/Card.vue')['default']
    Feature: typeof import('./../components/Feature.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    VButton: typeof import('./../components/shared/VButton.vue')['default']
    VCard: typeof import('./../components/VCard.vue')['default']
    VNavbar: typeof import('./../components/VNavbar.vue')['default']
  }
}

export { }
